language: node_js
node_js:
  - "node"
services:
    - mongodb
cache:
  directories:
    - ~/.npm
    - ~/.cache
install:
  - npm ci
script:
  - npm run watch & wait-on http://localhost:8080
  - $(npm bin)/cypress run --record